#!/usr/bin/env bash
node_modules/.bin/webpack \
  -p \
  --display-modules \
  --bail \
  --progress \
  --devtool sourcemap \
  --colors

IN_IFRAME=true node_modules/.bin/webpack \
  -p \
  --output-filename=iframe-videohub-player.js \
  --display-modules \
  --bail \
  --progress \
  --devtool sourcemap \
  --colors
